<?php
//$Id$

/**
 * Implements hook_permission().
 */
function my_text_block_permission(){     
	$arr = array();
	$arr['My text block access'] = array(
		'title' => t('My text block access'),
		'description' => t('View my text block'),
	);
	return $arr;
}

/**
 * Implements hook_block_info().
 */
function my_text_block_block_info() {
	$blocks = array();
	$blocks['my_text'] = array(
		'info' => t('Text block'),
		'cache' => DRUPAL_CACHE_GLOBAL,
	);
	return $blocks;
}
 
/**
 * Implements hook_block_view().
 */
function my_text_block_block_view($blockUID = '') {
	$block = array();
	if ($blockUID == 'my_text') {
      $block['subject'] = t('Text block');
      $block['content'] = 'My empty text.';
	}
	return $block;
}
